[package]
name = "sqlitexp"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]
edition = "2018"

[dependencies]
anyhow = "~1.0.39"
sqlx = { version = "~0.5.1", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "~1.4.0", features = ["macros", "rt"] }
